### ISSUE TITLE
How to get contact list from icloud?

### ISSUE THREAD

**Issue by deepakkumarrai** [tmyroadctfig/icloud4j#4]
Hi @tmyroadctfig , 

Please help me out, I am start working on project that require the access contact groups from icloud. so how can I access the contact groups from icloud use by this lib?.

**Comment by tmyroadctfig** [comment]
It looks like this is possible since it's supported by Pyicloud, but I haven't implemented it here yet. If you port across their work and submit a pull request I'll add it in.

Here are their current docs:
https://github.com/picklepete/pyicloud/tree/ced8e83a40764438b9f0de7f441b932411aaac97#contacts
And this is the implementation class:
https://github.com/picklepete/pyicloud/blob/ced8e83a40764438b9f0de7f441b932411aaac97/pyicloud/services/contacts.py

**Comment by deepakkumarrai** [comment]
Thanks @tmyroadctfig
